#spring:
#  profile:
#    active:
#    - dev
#---
#spring:
#  profiles: dev
#  application:
#    name: config-dev
#    
#---
#spring:
#  profiles: test
#  application:
#    name: config-test


spring:
  profile:
    active:
    - dev
---
server:
  port: 56080 #启动端口
spring:
  profiles: dev
  application:
    name: config-client

eureka:
  instance:
    hostname: eureka56080.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka56081.com:56081/eureka/,http://eureka56082.com:56082/eureka/

---
server:
  port: 56080 #启动端口
spring:
  profiles: test
  application:
    name: config-client

eureka:
  instance:
    hostname: eureka56080.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka56081.com:56081/eureka/,http://eureka56082.com:56082/eureka/
      